### ISSUE TITLE
把addendum改成中文，就报KeyError: 'feedback错误

### ISSUE THREAD

**Issue by chuangzhidan** [q2wxec/langgraph-demo#1]
PS D:\data\langgraph-demo-master\codeagent> python .\workflow.py
---GENERATE SOLUTION---
code_solution:To implement the merge sort algorithm in Python, you can define a function that recursively splits the input list into smaller sublists, sorts them, and then merges them back together in s
orted order.

Imports:
```python
# No specific imports are required for implementing merge sort
```

Code:
```python
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        merge_sort(left_half)
        merge_sort(right_half)

        i = j = k = 0

        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

    return arr
```

This `merge_sort` function takes a list `arr` as input and sorts it using the merge sort algorithm. It recursively divides the input list into smaller sublists until each sublist contains only one eleme
nt. Then it merges the sublists back together in sorted order.

You can use this function by passing a list to it, for example:
```python
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
sorted_list = merge_sort(my_list)
print(sorted_list)
```
---CHECKING CODE ---
mentor:{'correct': True}
Traceback (most recent call last):
  File "D:\data\langgraph-demo-master\codeagent\workflow.py", line 26, in <module>
    app.invoke({"keys": {"question": "如何实现归并排序算法？", "iterations": 0}})
  File "C:\Users\xie\AppData\Local\Programs\Python\Python39\lib\site-packages\langgraph\pregel\__init__.py", line 1171, in invoke
    for chunk in self.stream(
  File "C:\Users\xie\AppData\Local\Programs\Python\Python39\lib\site-packages\langgraph\pregel\__init__.py", line 774, in **stream
    "feedback": mentor['feedback'],
KeyError: 'feedback'**

**不知道为什么把addendum改成下面中文的，就报以上错误
addendum = """
--- --- ---
 你先前尝试解决过这个问题。
 这是你的解决方案：
 --- --- ---
 {generation}
 --- --- ---
 这是来自代码导师的指导：
 --- --- ---
 {feedback}
 --- --- ---
 请重新尝试回答这个问题。
 用对代码解决方案的描述，结构化你的答案。
 然后列出要导入的内容。
 最后列出功能性的代码块。

 用户的问题如下：
 --- --- ---
 {question}**

**Comment by chuangzhidan** [comment]
是缩进问题，打扰了
